FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

#------------------------------------------------------------------------------
#Added by thesis author
RUN apt-get update && apt-get -y install gcc portaudio19-dev python3-pyaudio 
#------------------------------------------------------------------------------

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]